config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  root "static_pages#home"
  get  "/help",    to: "static_pages#help"
  get  "/about",   to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup", to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :habits,          only: [:create, :show, :destroy]
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_form.html.erb
<%= form_with url: events_path, method: :post do |form| %>
  <%= form.hidden_field :habit_id, value: @habit.id %>
  <%= form.label :date %>
  <%= form.date_field :date %>
  <%= form.submit 'Mark Completed' %>
  <% end %>

app/views/shared/_habit_form.html.erb
<%= form_with(model: @habit) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Compose new habit..." %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Description" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.habits.count, "habit") %></span>